In [1]:
# Main imports
import pandas as pd
import numpy as np

# This method will need to be changed to non local method of accessing data
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [0]:
import glob
import numpy as np
import os
import pandas as pd
import pandas_profiling

In [0]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [0]:
abb_dir = os.listdir('gdrive/My Drive/airbnb')

In [0]:
data =  pd.read_csv('gdrive/My Drive/airbnb/listings_summary.csv')

In [0]:
scale_mapper2 = {'Private room': 1,
                 'Entire home/apt': 2,
                 'Shared room': 3}

scale_mapper = {'Real Bed': 1,
                'Pull-out Sofa':2,
                'Futon': 3,
                'Couch': 4,
                'Airbed': 5}

In [0]:
data['bed_type'] = data['bed_type'].replace(scale_mapper)   
data['room_type'] = data['room_type'].replace(scale_mapper2)

In [8]:
# Display first 5 observations to ensure proper creation of DataFrame
data.head()

     id  ... reviews_per_month
0  2015  ...              3.76
1  2695  ...              1.42
2  3176  ...              1.25
3  3309  ...              0.39
4  7071  ...              1.75

[5 rows x 96 columns]

In [9]:
# View column names
data.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       'notes', 'transit', 'access', 'interaction', 'house_rules',
       'thumbnail_url', 'medium_url', 'picture_url', 'xl_picture_url',
       'host_id', 'host_url', 'host_name', 'host_since', 'host_location',
       'host_about', 'host_response_time', 'host_response_rate',
       'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url',
       'host_picture_url', 'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'street',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country', 'latitude', 'longitude',
       'is_location_exact', 'property_type', 'room_type', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities', 'square_feet',
       'price', 'weekly_price', 'monthly_price', 'security_deposit',
       'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights',
       'maximum_nights', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'first_review', 'last_review', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'requires_license',
       'license', 'jurisdiction_names', 'instant_bookable',
       'is_business_travel_ready', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count', 'reviews_per_month'],
      dtype='object')

# Gather the right data

The model will only be exposed to certain data. For this reason, it is on necessary to train the model on certain types of
data from what is available. This CSV contains all of that data, so I will extract only the needed columns.

In [0]:
# Define the needed columns
columns = [
    'minimum_nights', 'bedrooms', 'bathrooms', 'accommodates', 
    'bed_type', 'security_deposit', 'room_type', 'zipcode', 
    'amenities', 'price'
]

# Select the subset from data
data_2 = data[columns]

In [11]:
# Check that the DataFrame has been altered in the expected way
data_2.head()

   minimum_nights  ...   price
0               4  ...  $60.00
1               2  ...  $17.00
2              62  ...  $90.00
3               5  ...  $26.00
4               2  ...  $42.00

[5 rows x 10 columns]

In [12]:
# Check dtypes on each column
for column in data_2.columns:
    print(
        f"{column}:\t{data_2[column].dtype}"
    )

minimum_nights:	int64
bedrooms:	float64
bathrooms:	float64
accommodates:	int64
bed_type:	int64
security_deposit:	object
room_type:	int64
zipcode:	object
amenities:	object
price:	object

# Get the data in the right format

Some of the data that should be in a numeric data type is currently a string. The amenities looks like it was poorly converted
from JSON format. The data will need to be cleaned before we can use it to make any predictions.

In [0]:
# Create a function to clean the security deposit column
def clean_security_deposit(value):
    """
    Function accepts single value inputs. If the value is a string, 
    it will strip the '$' and ',' out of the string before converting
    the string to an integer.
    """
    try:
        if type(value) != str:
            return value
        else:
            new_value = value.replace("$", "")
            new_value_2 = new_value.replace(",","")
            return int(float(new_value_2))
    except:
        new_value = str(value).replace("$", "")
        new_value_2 = new_value.replace(",", "")
        return int(float(new_value_2))

In [0]:
# Create a function to clean the zipcode column
def clean_zipcode(value):
    """
    Function accepts single value inputs. If the regex pattern is matched, 
    return the match. 
    """
    if type(value) != str:
        return value
    else:
        pattern = '\d+'
        result = re.findall(pattern, value)
        return int(result[0])

In [0]:
# Create a function to clean the price column
def clean_price(value):
    """
    Function accepts single value inputs. If the is a string,
    it will strip the '$' and ',' out of the string before converting
    the string to a float.
    """
    try:
        if type(value) != str:
            return value
        else:
            new_value = value.replace("$", "")
            new_value_2 = new_value.replace(",", "")
            return float(new_value_2)
    except:
        new_value = str(value).replace("$", "")
        new_value_2 = new_value.replace(",", "")
        return float(new_value_2)

In [0]:
# Create function to pull needed amenities out into a list
def fix_amenities(value):
    """
    Function accepts single value inputs. If the regex pattern is matched, 
    it will return a list of all values that match and are represented as
    an amenity that we want.
    """
    pattern = '\w+\s?\w+\s?\w+\s?\w+|\w+\s?\w+\s?\w+|\w+\s?\w+|\w+'
    result = re.findall(pattern, value.lower())
    return result

In [0]:
# Import re for regex matching
import re


# Apply functions to DataFrame columns
data_3 = data_2.copy()
data_3['security_deposit'] = data_2['security_deposit'].apply(clean_security_deposit)
data_3['zipcode'] = data_2['zipcode'].apply(clean_zipcode)
data_3['price'] = data_2['price'].apply(clean_price)

# Fix amenities to work with function
data_3['amenities'] = data_2['amenities'].apply(fix_amenities)

In [0]:
# OneHot encode amenities
data_3 = data_3.drop('amenities', 1).join(data_3['amenities'].str.join('|').str.get_dummies())
# Remove nans, unable to impute accurately
data_final = data_3.dropna()

In [19]:
data_final.head()

   minimum_nights  bedrooms  bathrooms  ...  wifi  window guards  wireless intercom
0               4      1.00       1.00  ...     1              0                  0
1               2      1.00       1.00  ...     1              0                  0
2              62      1.00       1.00  ...     1              0                  1
3               5      1.00       1.00  ...     1              0                  1
4               2      1.00       1.00  ...     1              0                  0

[5 rows x 161 columns]

In [20]:
data_3.head()

   minimum_nights  bedrooms  bathrooms  ...  wifi  window guards  wireless intercom
0               4      1.00       1.00  ...     1              0                  0
1               2      1.00       1.00  ...     1              0                  0
2              62      1.00       1.00  ...     1              0                  1
3               5      1.00       1.00  ...     1              0                  1
4               2      1.00       1.00  ...     1              0                  0

[5 rows x 161 columns]

In [21]:
!pip install category_encoders

Requirement already satisfied: category_encoders in /usr/local/lib/python3.6/dist-packages (2.1.0)
Requirement already satisfied: pandas>=0.21.1 in /usr/local/lib/python3.6/dist-packages (from category_encoders) (0.25.3)
Requirement already satisfied: numpy>=1.11.3 in /usr/local/lib/python3.6/dist-packages (from category_encoders) (1.17.5)
Requirement already satisfied: patsy>=0.4.1 in /usr/local/lib/python3.6/dist-packages (from category_encoders) (0.5.1)
Requirement already satisfied: statsmodels>=0.6.1 in /usr/local/lib/python3.6/dist-packages (from category_encoders) (0.10.2)
Requirement already satisfied: scipy>=0.19.0 in /usr/local/lib/python3.6/dist-packages (from category_encoders) (1.4.1)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.6/dist-packages (from category_encoders) (0.22.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.21.1->category_encoders) (2.6.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.21.1->category_encoders) (2018.9)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from patsy>=0.4.1->category_encoders) (1.12.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn>=0.20.0->category_encoders) (0.14.1)

In [0]:
# Import sklearn modules
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from category_encoders import OrdinalEncoder, OneHotEncoder

In [0]:
# Train / Test split
# Split into feature matrix and target vector


target = 'price'

X = data_final.drop(columns=target)
y = data_final[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

In [24]:
X_train['laundry'] = np.zeros(len(X_train))
X_train['security'] = np.zeros(len(X_train))
X_train['patio'] = np.zeros(len(X_train))
X_train['spa'] = np.zeros(len(X_train))
X_train['cleaning'] = np.zeros(len(X_train))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [25]:
X_train['laundry'] = X_train['laundry'].astype(int)
X_train['security'] = X_train['security'].astype(int)
X_train['patio'] = X_train['patio'].astype(int)
X_train['spa'] = X_train['spa'].astype(int)
X_train['cleaning'] = X_train['cleaning'].astype(int)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [26]:
X_test['laundry'] = np.zeros(len(X_test))
X_test['security'] = np.zeros(len(X_test))
X_test['patio'] = np.zeros(len(X_test))
X_test['spa'] = np.zeros(len(X_test))
X_test['cleaning'] = np.zeros(len(X_test))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [27]:
X_test['laundry'] = X_test['laundry'].astype(int)
X_test['security'] = X_test['security'].astype(int)
X_test['patio'] = X_test['patio'].astype(int)
X_test['spa'] = X_test['spa'].astype(int)
X_test['cleaning'] = X_test['cleaning'].astype(int)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [28]:
# Create Pipeline
pipeline = Pipeline(
    [('encoder', OrdinalEncoder()),
     ('model', LinearRegression())]
)

pipeline.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('encoder',
                 OrdinalEncoder(cols=[], drop_invariant=False,
                                handle_missing='value', handle_unknown='value',
                                mapping=[], return_df=True, verbose=0)),
                ('model',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=False))],
         verbose=False)

In [0]:
y_pred = pipeline.predict(X_train)

In [30]:
mean_squared_error(y_train, y_pred)

61222.268338448404

# Not great, but it's something

The results aren't amazing, actually fairly far from it. But at least this is giving us _something_

In [0]:
# Lets create a new set of data subset from only the highest review scores
new_data = data[data['review_scores_value']>=9]

In [0]:
# Pull out only the columns we care about
subset_data = new_data[columns]

In [0]:
# Impute 0 for security deposit if NaN
df = subset_data.copy()
df['security_deposit'] = df['security_deposit'].fillna(0)

In [0]:
# Drop other NaN values, they can't be imputed accurately
df = df.dropna()

In [0]:
# Clean the data
df['security_deposit'] = df['security_deposit'].apply(clean_security_deposit)
df['price'] = df['price'].apply(clean_price)
df['zipcode'] = df['zipcode'].apply(clean_zipcode)
df['amenities'] = df['amenities'].apply(fix_amenities)

In [36]:
df

       minimum_nights  ...  price
0                   4  ...  60.00
1                   2  ...  17.00
2                  62  ...  90.00
3                   5  ...  26.00
4                   2  ...  42.00
...               ...  ...    ...
22346               1  ...  18.00
22352               1  ...  40.00
22367               1  ...  50.00
22398               2  ...  45.00
22401               1  ... 170.00

[15911 rows x 10 columns]

In [0]:
# OneHot amenities
df = df.join(df['amenities'].str.join('|').str.get_dummies())

In [0]:
# Drop amenities column
df = df.drop('amenities', 1)

In [0]:
# Re-sort amenities by occurance
amenity_count = dict()

for column in df:
    if column in columns:
        pass
    else:
        amenity_count[column] = df[column].value_counts().to_dict()
        
# Set to dataframe to sort
df_amenities = pd.DataFrame(amenity_count)

# Create list of popular index
amenities = df_amenities.iloc[1].sort_values(ascending=False)[:52].index.to_list()

# Remove nonsense indicies
amenities.remove('en')
amenities.remove('in')
amenities.remove('translation missing')
amenities.remove('hosting_amenity_50')
amenities.remove('hosting_amenity_49')

In [0]:
# Feed new data through the pipeline

# Split into feature matrix / target vector
new_columns = [
    'minimum_nights', 'bedrooms', 'bathrooms', 'accommodates', 
    'bed_type', 'security_deposit', 'room_type', 'zipcode', 
    'price'
]

X = df[new_columns + amenities].drop(columns=target)
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

In [0]:
# Fit ridge regressor as baseline model
from sklearn.linear_model import Ridge
model = Pipeline(
    [('encoder', OrdinalEncoder()), 
     ('reg', Ridge(alpha=10, solver='auto', tol=0.05))]
)

In [42]:
model.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('encoder',
                 OrdinalEncoder(cols=[], drop_invariant=False,
                                handle_missing='value', handle_unknown='value',
                                mapping=[], return_df=True, verbose=0)),
                ('reg',
                 Ridge(alpha=10, copy_X=True, fit_intercept=True, max_iter=None,
                       normalize=False, random_state=None, solver='auto',
                       tol=0.05))],
         verbose=False)

In [43]:
model.score(X_train, y_train) # r^2 is 8%

0.08110959807915175

In [0]:
y_pred = model.predict(X_test)

In [45]:
y_pred[:5]

array([86.61193121, 47.79530451, 16.47172705, 80.0104625 , 94.52625868])

In [46]:
y_test[:5]

11300   60.00
14162   40.00
9454    25.00
16880   27.00
1404    75.00
Name: price, dtype: float64

In [0]:
import matplotlib.pyplot as plt
plt.scatter(y_pred, y_test)
plt.show()

In [0]:
# Create truncation function -> min 15
y_pred_2 = [15.0 if x < 15.0 else round(x) for x in y_pred]

In [49]:
# Calc R^2 score for truncated predictions
from sklearn.metrics import r2_score


r2_score(y_test, y_pred_2)

0.20528258819205647

# An improvement

This model scores 20% r-squared, which is an improvement over the original baseline model.

In [0]:
# Save the model object
import pickle

file_model = open('model.obj', 'wb')
pickle.dump(model, file_model)

In [0]:
file_model.close()

In [52]:
X_train.head()

       minimum_nights  bedrooms  ...  private living room  bathtub
4730                1      1.00  ...                    0        0
13957              10      1.00  ...                    0        0
18166               2      1.00  ...                    0        0
14578               1      1.00  ...                    0        0
4655                4      1.00  ...                    0        0

[5 rows x 55 columns]

In [53]:
X_train.bed_type.value_counts()

1    13053
2      278
3      140
4       42
5       11
Name: bed_type, dtype: int64

In [54]:
X_train.room_type.value_counts()

1    6993
2    6382
3     149
Name: room_type, dtype: int64

In [55]:
X_train.head()

       minimum_nights  bedrooms  ...  private living room  bathtub
4730                1      1.00  ...                    0        0
13957              10      1.00  ...                    0        0
18166               2      1.00  ...                    0        0
14578               1      1.00  ...                    0        0
4655                4      1.00  ...                    0        0

[5 rows x 55 columns]

In [0]:
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OrdinalEncoder

In [0]:
# Have to ordinal encode bed_type, room_type

In [57]:
X_train.head()

       minimum_nights  bedrooms  ...  private living room  bathtub
4730                1      1.00  ...                    0        0
13957              10      1.00  ...                    0        0
18166               2      1.00  ...                    0        0
14578               1      1.00  ...                    0        0
4655                4      1.00  ...                    0        0

[5 rows x 55 columns]

In [0]:
model = XGBClassifier()
model.fit(X_train, y_train)

In [60]:
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]

accuracy = accuracy_score(y_test, predictions)
print('Accuracy: %.2f%%' % (accuracy * 100.0))

Accuracy: 7.75%

4730    40.00
13957   55.00
18166   29.00
14578   35.00
4655    45.00
Name: price, dtype: float64

In [0]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [65]:
from tensorflow.keras.models import Sequential, Model

X_train.head()

       minimum_nights  bedrooms  ...  private living room  bathtub
4730                1      1.00  ...                    0        0
13957              10      1.00  ...                    0        0
18166               2      1.00  ...                    0        0
14578               1      1.00  ...                    0        0
4655                4      1.00  ...                    0        0

[5 rows x 55 columns]

In [67]:
X_train.shape

(13524, 55)

In [70]:
model = tf.keras.Sequential()
model.add(layers.Dense(64, input_shape=(55,), activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(1, activation='relu'))

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.

In [0]:
from statistics import mean

In [0]:
model.compile(optimizer='adam', loss='mse')

In [77]:
model.fit(X_train,y_train,epochs=50,batch_size=128)

Train on 13524 samples
Epoch 1/50
13524/13524 [==============================] - 1s 51us/sample - loss: 24844.0419
Epoch 2/50
13524/13524 [==============================] - 0s 20us/sample - loss: 23595.1819
Epoch 3/50
13524/13524 [==============================] - 0s 17us/sample - loss: 23595.1832
Epoch 4/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1829
Epoch 5/50
13524/13524 [==============================] - 0s 20us/sample - loss: 23595.1826
Epoch 6/50
13524/13524 [==============================] - 0s 19us/sample - loss: 23595.1826
Epoch 7/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1823
Epoch 8/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1816
Epoch 9/50
13524/13524 [==============================] - 0s 17us/sample - loss: 23595.1833
Epoch 10/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1827
Epoch 11/50
13524/13524 [==============================] - 0s 17us/sample - loss: 23595.1834
Epoch 12/50
13524/13524 [==============================] - 0s 17us/sample - loss: 23595.1830
Epoch 13/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1822
Epoch 14/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1821
Epoch 15/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1820
Epoch 16/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1818
Epoch 17/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1820
Epoch 18/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1821
Epoch 19/50
13524/13524 [==============================] - 0s 19us/sample - loss: 23595.1834
Epoch 20/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1833
Epoch 21/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1829
Epoch 22/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1830
Epoch 23/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1824
Epoch 24/50
13524/13524 [==============================] - 0s 19us/sample - loss: 23595.1827
Epoch 25/50
13524/13524 [==============================] - 0s 19us/sample - loss: 23595.1824
Epoch 26/50
13524/13524 [==============================] - 0s 19us/sample - loss: 23595.1829
Epoch 27/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1831
Epoch 28/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1816
Epoch 29/50
13524/13524 [==============================] - 0s 21us/sample - loss: 23595.1829
Epoch 30/50
13524/13524 [==============================] - 0s 17us/sample - loss: 23595.1840
Epoch 31/50
13524/13524 [==============================] - 0s 17us/sample - loss: 23595.1820
Epoch 32/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1810
Epoch 33/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1819
Epoch 34/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1829
Epoch 35/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1825
Epoch 36/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1828
Epoch 37/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1823
Epoch 38/50
13524/13524 [==============================] - 0s 17us/sample - loss: 23595.1828
Epoch 39/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1828
Epoch 40/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1830
Epoch 41/50
13524/13524 [==============================] - 0s 17us/sample - loss: 23595.1830
Epoch 42/50
13524/13524 [==============================] - 0s 17us/sample - loss: 23595.1826
Epoch 43/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1826
Epoch 44/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1818
Epoch 45/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1848
Epoch 46/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1835
Epoch 47/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1825
Epoch 48/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1828
Epoch 49/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1828
Epoch 50/50
13524/13524 [==============================] - 0s 18us/sample - loss: 23595.1823